// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function FetchDirectory(arg1) {
  return window['go']['main']['App']['FetchDirectory'](arg1);
}

export function FetchSourceList(arg1) {
  return window['go']['main']['App']['FetchSourceList'](arg1);
}

export function OpenFileDir(arg1) {
  return window['go']['main']['App']['OpenFileDir'](arg1);
}

export function PerformSelfUpdate(arg1, arg2) {
  return window['go']['main']['App']['PerformSelfUpdate'](arg1, arg2);
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}
