// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAppUpdate():Promise<main.CheckResult>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function DownloadFilesAsZip(arg1:Array<main.DownloadItem>,arg2:string):Promise<void>;

export function FetchDirectory(arg1:string):Promise<any>;

export function FetchSourceList(arg1:string):Promise<Record<string, main.SourceConfig>>;

export function OpenFileDir(arg1:string):Promise<void>;

export function PerformSelfUpdate(arg1:string,arg2:string):Promise<void>;

export function SelectSavePath(arg1:string):Promise<string>;
