// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function FetchDirectory(arg1:string):Promise<main.FileNode>;

export function FetchSourceList(arg1:string):Promise<Record<string, main.SourceConfig>>;

export function OpenFileDir(arg1:string):Promise<void>;

export function SelectSavePath(arg1:string):Promise<string>;
